<?php

namespace Colegio\BoletinBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BoletinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoletinRepository extends EntityRepository
{
}
