docente:
    pattern:  /
    defaults: { _controller: "ColegioDocenteBundle:Docente:index" }

docente_show:
    pattern:  /{id}/show
    defaults: { _controller: "ColegioDocenteBundle:Docente:show" }

docente_new:
    pattern:  /new
    defaults: { _controller: "ColegioDocenteBundle:Docente:new" }

docente_create:
    pattern:  /create
    defaults: { _controller: "ColegioDocenteBundle:Docente:create" }
    requirements: { _method: post }

docente_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ColegioDocenteBundle:Docente:edit" }

docente_update:
    pattern:  /{id}/update
    defaults: { _controller: "ColegioDocenteBundle:Docente:update" }
    requirements: { _method: post|put }

docente_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ColegioDocenteBundle:Docente:delete" }
    requirements: { _method: post|delete }
