parameters:
#    tucolegio_ppal.example.class: Tucolegio\PpalBundle\Example

services:
#    tucolegio_ppal.example:
#        class: %tucolegio_ppal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
