colegio_grupo_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ColegioGrupoBundle:Default:index }

ColegioGrupoBundle_asignatura:
    resource: "@ColegioGrupoBundle/Resources/config/routing/asignatura.yml"
    prefix:   /asignatura

ColegioGrupoBundle_grupo:
    resource: "@ColegioGrupoBundle/Resources/config/routing/grupo.yml"
    prefix:   /grupo

ColegioGrupoBundle_grupoasignatura:
    resource: "@ColegioGrupoBundle/Resources/config/routing/grupoasignatura.yml"
    prefix:   /grupoasignatura
    
ColegioGrupoBundle_nivel:
    resource: "@ColegioGrupoBundle/Resources/config/routing/nivel.yml"
    prefix:   /nivel
    

