colegio_grupo_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ColegioGrupoBundle:Default:index }

ColegioGrupoBundle_asignatura:
    resource: "@ColegioGrupoBundle/Resources/config/routing/asignatura.yml"
    prefix:   /asignatura
