parameters:
#    colegio_grupo.example.class: Colegio\GrupoBundle\Example

services:
#    colegio_grupo.example:
#        class: %colegio_grupo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
