colegio_boletin:
    resource: "@ColegioBoletinBundle/Resources/config/routing.yml"
    prefix:   /boletin

colegio_docente:
    resource: "@ColegioDocenteBundle/Resources/config/routing.yml"
    prefix:   /docente

colegio_grupo:
    resource: "@ColegioGrupoBundle/Resources/config/routing.yml"
    prefix:   /grupo

colegio_estudiante:
    resource: "@ColegioEstudianteBundle/Resources/config/routing.yml"
    prefix:   /estudiante
    
ColegioEstudianteBundle_grupoestudiante:
    resource: "@ColegioEstudianteBundle/Resources/config/routing.yml"
    prefix:   /grupoestudiante
    

ColegioEstudianteBundle_nota:
    resource: "@ColegioEstudianteBundle/Resources/config/routing.yml"
    prefix:   /nota    

temas_temas:
    resource: "@TemasTemasBundle/Resources/config/routing.yml"
    prefix:   /temas

colegio_admin:
    resource: "@ColegioAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

ColegioGrupoBundle_asignatura:
    resource: "@ColegioGrupoBundle/Resources/config/routing.yml"
    prefix:   /asignatura
