usuarios_login:
    pattern:  /login
    defaults: { _controller: UsuariosUsuariosBundle:Default:login }

usuarios_login_check:
    pattern:  /login_check

ColegioAdminBundle_logout:
    pattern:  /logout

usuarios_usuarios:
    resource: "@UsuariosUsuariosBundle/Resources/config/routing.yml"
    prefix:   /usuarios

colegio_boletin:
    resource: "@ColegioBoletinBundle/Resources/config/routing.yml"
    prefix:   /boletin

colegio_docente:
    resource: "@ColegioDocenteBundle/Resources/config/routing.yml"
    prefix:   /docente

ColegioGrupoBundle_grupo:
    resource: "@ColegioGrupoBundle/Resources/config/routing.yml"
    prefix:   /grupo

colegio_estudiante:
    resource: "@ColegioEstudianteBundle/Resources/config/routing.yml"
    prefix:   /estudiante

temas_temas:
    resource: "@TemasTemasBundle/Resources/config/routing.yml"
    prefix:   /temas

colegio_admin:
    resource: "@ColegioAdminBundle/Resources/config/routing.yml"
    prefix:   /admin


