usuarios_usuarios:
    resource: "@UsuariosUsuariosBundle/Resources/config/routing.yml"
    prefix:   /usuarios

colegio_boletin:
    resource: "@ColegioBoletinBundle/Resources/config/routing.yml"
    prefix:   /boletin

colegio_docente:
    resource: "@ColegioDocenteBundle/Resources/config/routing.yml"
    prefix:   /docente

colegio_estudiante:
    resource: "@ColegioEstudianteBundle/Resources/config/routing.yml"
    prefix:   /estudiante

temas_temas:
    resource: "@TemasTemasBundle/Resources/config/routing.yml"
    prefix:   /temas

colegio_admin:
    resource: "@ColegioAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

ColegioGrupoBundle_grupo:
    resource: "@ColegioGrupoBundle/Resources/config/routing.yml"
    prefix:   /grupo
