security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_ADMIN]
    firewalls:
      backsedes:
        pattern:     ^/admin
        provider:    Usuarios
        anonymous:   ~
        form_login: 
          default_target_path: /admin/
          login_path: /admin/login
          check_path: /admin/login_check
        logout:
          path:       admin_logout
          target:     /admin/login
    
        remember_me:
           key: jairocris1234
           lifetime: 3600
    
    access_control:
      - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin/*, roles: ROLE_ADMIN }

    providers:
        Usuarios:
         entity: { class: Colegio\AdminBundle\Entity\Usuarios, property:username }
    encoders:
         Colegio\AdminBundle\Entity\Usuarios: { algorithm: sha512, iterations: 10 }