security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    
    firewalls:
      admin:
        pattern:     ^/*
        provider:    Usuarios
        anonymous:   ~
        form_login:  
          default_target_path: /admin/
          always_use_default_target_path: true
          login_path: /admin/login
          check_path: /admin/login_check
        logout:
          path:       usuarios_logout
          target:     /
          invalidate_session: false
        switch_user: true   
        remember_me:
           key: jairocris1234
           lifetime: 3600
    
      
    
 
    access_control:
      - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
      - { path: ^/grupo/*, roles: ROLE_SUPER_ADMIN }
      - { path: ^/usuarios/*, roles: ROLE_SUPER_ADMIN }
      - { path: ^/admin/estrato/*, roles: ROLE_SUPER_ADMIN }
      - { path: ^/admin/estadocolegio/*, roles: ROLE_SUPER_ADMIN }
      - { path: ^/admin/departamento/*, roles: ROLE_SUPER_ADMIN }
      - { path: ^/admin/jornada/*, roles: ROLE_SUPER_ADMIN }
      - { path: ^/admin/localidad/*, roles: ROLE_SUPER_ADMIN }
      - { path: ^/admin/municipio/*, roles: ROLE_SUPER_ADMIN }
      - { path: ^/admin/tipocolegio/*, roles: ROLE_SUPER_ADMIN }
      - { path: ^/admin/grupos/nivel/*, roles: ROLE_SUPER_ADMIN }
      
      - { path: ^/admin/perfil/*, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
      - { path: ^/admin/colegio/new , roles: ROLE_SUPER_ADMIN }
      
      - { path: ^/admin/direccion/new, roles: ROLE_SUPER_ADMIN }
      
      - { path: ^/admin/, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
      
     
      

    providers:
          chain_provider:
             chain:
                 providers: [Usuarios,in_memory]
          Usuarios:
             entity: { class: Usuarios\UsuariosBundle\Entity\Usuarios, property:username }

          in_memory: 
                 memory:
                     users:
                         arturo   :  { password: 12345, roles: 'ROLE_SUPER_ADMIN' }
                         alonso   :  { password: 12345, roles: 'ROLE_SUPER_ADMIN' }
         
    encoders:
         Usuarios\UsuariosBundle\Entity\Usuarios: { algorithm: sha512, iterations: 10 }
         Symfony\Component\Security\Core\User\User: plaintext