usuarios_usuarios_homepage:
    pattern:  /
    defaults: { _controller: UsuariosUsuariosBundle:Default:index }

UsuariosUsuariosBundle_usuarios:
    resource: "@UsuariosUsuariosBundle/Resources/config/routing/usuarios.yml"
    prefix:   /usuarios