usuarios_usuarios_homepage:
    pattern:  /
    defaults: { _controller: UsuariosUsuariosBundle:Default:index }

usuariosBundle_usuarios:
    resource: "@UsuariosUsuariosBundle/Resources/config/routing/usuarios.yml"
    prefix:   /usuarios

UsuariosUsuariosBundle_tipousuario:
    resource: "@UsuariosUsuariosBundle/Resources/config/routing/tipousuario.yml"
    prefix:   /tipousuario