usuarios_login:
    pattern:  /login
    defaults: { _controller: UsuariosUsuariosBundle:Default:login }

usuarios_login_check:
    pattern:  /login_check

usuarios_logout:
    pattern:  /logout

usuarios_usuarios_homepage:
    pattern:  /
    defaults: { _controller: UsuariosUsuariosBundle:Default:index }

UsuariosUsuariosBundle_usuarios:
    resource: "@UsuariosUsuariosBundle/Resources/config/routing/usuarios.yml"
    prefix:   /usuarios

UsuariosUsuariosBundle_tipousuario:
    resource: "@UsuariosUsuariosBundle/Resources/config/routing/tipousuario.yml"
    prefix:   /tipousuario
