<?php

namespace Colegio\EstudianteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GrupoEstudianteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoEstudianteRepository extends EntityRepository
{
}
