estrato:
    pattern:  /
    defaults: { _controller: "ColegioAdminBundle:Estrato:index" }

estrato_show:
    pattern:  /{id}/show
    defaults: { _controller: "ColegioAdminBundle:Estrato:show" }

estrato_new:
    pattern:  /new
    defaults: { _controller: "ColegioAdminBundle:Estrato:new" }

estrato_create:
    pattern:  /create
    defaults: { _controller: "ColegioAdminBundle:Estrato:create" }
    requirements: { _method: post }

estrato_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ColegioAdminBundle:Estrato:edit" }

estrato_update:
    pattern:  /{id}/update
    defaults: { _controller: "ColegioAdminBundle:Estrato:update" }
    requirements: { _method: post|put }

estrato_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ColegioAdminBundle:Estrato:delete" }
    requirements: { _method: post|delete }
