usuarios:
    pattern:  /
    defaults: { _controller: "ColegioAdminBundle:Usuarios:index" }

usuarios_show:
    pattern:  /{id}/show
    defaults: { _controller: "ColegioAdminBundle:Usuarios:show" }

usuarios_new:
    pattern:  /new
    defaults: { _controller: "ColegioAdminBundle:Usuarios:new" }

usuarios_create:
    pattern:  /create
    defaults: { _controller: "ColegioAdminBundle:Usuarios:create" }
    requirements: { _method: post }

usuarios_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ColegioAdminBundle:Usuarios:edit" }

usuarios_update:
    pattern:  /{id}/update
    defaults: { _controller: "ColegioAdminBundle:Usuarios:update" }
    requirements: { _method: post|put }

usuarios_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ColegioAdminBundle:Usuarios:delete" }
    requirements: { _method: post|delete }
