<?php

namespace Colegio\GrupoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AsignaturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignaturaRepository extends EntityRepository
{
}
