parameters:
#    colegio_admin.example.class: Colegio\AdminBundle\Example

services:
#    colegio_admin.example:
#        class: %colegio_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
