<?php

namespace Colegio\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstadoColegioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoColegioRepository extends EntityRepository
{
}
