<?php

namespace Colegio\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SedeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SedeRepository extends EntityRepository
{   
    public function findColegio($id)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT u FROM ColegioAdminBundle:Sede u JOIN u.idDetalleColegio p 
            WHERE p.idColegio = :id  
            
        ');
        $consulta->setParameter('id', $id);
        return $consulta->getResult();
    }
}
