<?php

namespace Colegio\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoColegioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoColegioRepository extends EntityRepository
{
}
